### ISSUE TITLE
Use env vars for stack config

### ISSUE THREAD

**Issue by hisapy** [iporaitech/pwr2-docker#32]
The declare the following variables in **docker-compose.dev.example.yml** 

``` yaml
environment:
    MIX_ENV: dev
    NODE_ENV: development
    HTTP_PORT: 4001
    HTTPS_PORT: 4443
    GRAPHQL_URL: http://localhost:4001/graphql
    # database
    DB_HOST: db
    DB_NAME: webapp_dev
    DB_USER: postgres
    DB_USER_PASSWORD:
    # mailer
    MAILER_SERVER: localhost
    MAILER_USERNAME: dev_user
    MAILER_PASSWORD: dev_password
```

and use them in the corresponding parts of the stack, both backend and front-end:
- babelRelayPlugin.js
- config/*.exs
- other .js and .exs$ files.
